"""change size to enum type

Revision ID: 1061beb793f7
Revises: d46e34c86204
Create Date: 2023-12-23 22:12:29.135807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1061beb793f7"
down_revision: Union[str, None] = "d46e34c86204"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "size",
        existing_type=mysql.VARCHAR(length=5),
        type_=sa.Enum("SMALL", "LARGE", name="productsize"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "size",
        existing_type=sa.Enum("SMALL", "LARGE", name="productsize"),
        type_=mysql.VARCHAR(length=5),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
