"""add disabled to user

Revision ID: cd8be0a48ba0
Revises: 8944e8c272d4
Create Date: 2023-12-23 20:09:11.045617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd8be0a48ba0"
down_revision: Union[str, None] = "8944e8c272d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("disabled", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "disabled")
    # ### end Alembic commands ###
