"""name chosung col

Revision ID: d46e34c86204
Revises: cd8be0a48ba0
Create Date: 2023-12-23 22:02:19.382377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d46e34c86204"
down_revision: Union[str, None] = "cd8be0a48ba0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("name_chosung", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "name_chosung")
    # ### end Alembic commands ###
